### ISSUE TITLE
VPN's?

### ISSUE THREAD

**Issue by Charles-IV** [HackerExperience/GameDesign#13]
Maybe vpn's could be added, such as a vpn virus that you can upload to a machine you hacked, and ip's in logs point to the machine you hacked.
There could also be a paid vpn service?
To balance out, maybe the vpn virus should only work while the machine with the virus on is online.

Sorry if this was already being planned.

**Comment by PedroHLC** [comment]
Sorry, you want to use one machine as proxy to hack another?
If yes, we do have this feature and we call it "bounce". As long as you know someone ip and psw you can bounce through them to another machine, and through that machine to another and keep doing this until your target.
For example, let's suppose I hacked kress, through kress I hacked charlotte, through charlotte I hacked renato, and through renato I hacked blackdawn, I can then on the app "Connectin Manager" save this bounce with the name "darude-sandstorm"
So I have the bounce:
`Darude-Sandstorm: myserver1 > kress > charlotte > renato > blackdawn`
Every time I do something in blackdawn server, in its logs renato did it, in renato's logs charlotte did it, in charlotte's logs kress did it, and of course I'm deleting my logs on kress because I 0wn3d him...

**Comment by Charles-IV** [comment]
Yes, I've just seen the bouce feature on the youtube video, which is essentially what i was thinking.
I don't know enough about it, but maybe the idea of a paid service? where you don't have to know the ip and psw, but you do pay. This can have the added security of people not being able to read the logs, or something else, unless your cracker is good enough to hack the provider.

Im applying knowledge/context from legacy here, so sorry if it doesn't apply.

**Comment by PedroHLC** [comment]
😜 renato did a lot of planning on this part of gameplay. I'm not sure about the paid service, it's important to keep the game balanced. It would be better if we start doing open sessions of gaming planning for things like this. I would love to implement a onion-like super secure thing too, but that would make the game unplayable for n00bs.
